// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cipher-bot/ent/predicate"
	"cipher-bot/ent/request"
	"cipher-bot/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestUpdate is the builder for updating Request entities.
type RequestUpdate struct {
	config
	hooks    []Hook
	mutation *RequestMutation
}

// Where appends a list predicates to the RequestUpdate builder.
func (ru *RequestUpdate) Where(ps ...predicate.Request) *RequestUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetUpdatedAt sets the "updated_at" field.
func (ru *RequestUpdate) SetUpdatedAt(t time.Time) *RequestUpdate {
	ru.mutation.SetUpdatedAt(t)
	return ru
}

// SetStatus sets the "status" field.
func (ru *RequestUpdate) SetStatus(r request.Status) *RequestUpdate {
	ru.mutation.SetStatus(r)
	return ru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ru *RequestUpdate) SetNillableStatus(r *request.Status) *RequestUpdate {
	if r != nil {
		ru.SetStatus(*r)
	}
	return ru
}

// SetType sets the "type" field.
func (ru *RequestUpdate) SetType(r request.Type) *RequestUpdate {
	ru.mutation.SetType(r)
	return ru
}

// SetAlgorithm sets the "algorithm" field.
func (ru *RequestUpdate) SetAlgorithm(r request.Algorithm) *RequestUpdate {
	ru.mutation.SetAlgorithm(r)
	return ru
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (ru *RequestUpdate) SetNillableAlgorithm(r *request.Algorithm) *RequestUpdate {
	if r != nil {
		ru.SetAlgorithm(*r)
	}
	return ru
}

// ClearAlgorithm clears the value of the "algorithm" field.
func (ru *RequestUpdate) ClearAlgorithm() *RequestUpdate {
	ru.mutation.ClearAlgorithm()
	return ru
}

// SetKeyMode sets the "key_mode" field.
func (ru *RequestUpdate) SetKeyMode(rm request.KeyMode) *RequestUpdate {
	ru.mutation.SetKeyMode(rm)
	return ru
}

// SetNillableKeyMode sets the "key_mode" field if the given value is not nil.
func (ru *RequestUpdate) SetNillableKeyMode(rm *request.KeyMode) *RequestUpdate {
	if rm != nil {
		ru.SetKeyMode(*rm)
	}
	return ru
}

// ClearKeyMode clears the value of the "key_mode" field.
func (ru *RequestUpdate) ClearKeyMode() *RequestUpdate {
	ru.mutation.ClearKeyMode()
	return ru
}

// SetManualKeyValidation sets the "manual_key_validation" field.
func (ru *RequestUpdate) SetManualKeyValidation(b bool) *RequestUpdate {
	ru.mutation.SetManualKeyValidation(b)
	return ru
}

// SetNillableManualKeyValidation sets the "manual_key_validation" field if the given value is not nil.
func (ru *RequestUpdate) SetNillableManualKeyValidation(b *bool) *RequestUpdate {
	if b != nil {
		ru.SetManualKeyValidation(*b)
	}
	return ru
}

// ClearManualKeyValidation clears the value of the "manual_key_validation" field.
func (ru *RequestUpdate) ClearManualKeyValidation() *RequestUpdate {
	ru.mutation.ClearManualKeyValidation()
	return ru
}

// SetUserID sets the "user_id" field.
func (ru *RequestUpdate) SetUserID(i int) *RequestUpdate {
	ru.mutation.SetUserID(i)
	return ru
}

// SetUser sets the "user" edge to the User entity.
func (ru *RequestUpdate) SetUser(u *User) *RequestUpdate {
	return ru.SetUserID(u.ID)
}

// Mutation returns the RequestMutation object of the builder.
func (ru *RequestUpdate) Mutation() *RequestMutation {
	return ru.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ru *RequestUpdate) ClearUser() *RequestUpdate {
	ru.mutation.ClearUser()
	return ru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RequestUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	ru.defaults()
	if len(ru.hooks) == 0 {
		if err = ru.check(); err != nil {
			return 0, err
		}
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RequestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ru.check(); err != nil {
				return 0, err
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			if ru.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RequestUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RequestUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RequestUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ru *RequestUpdate) defaults() {
	if _, ok := ru.mutation.UpdatedAt(); !ok {
		v := request.UpdateDefaultUpdatedAt()
		ru.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *RequestUpdate) check() error {
	if v, ok := ru.mutation.Status(); ok {
		if err := request.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Request.status": %w`, err)}
		}
	}
	if v, ok := ru.mutation.GetType(); ok {
		if err := request.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Request.type": %w`, err)}
		}
	}
	if v, ok := ru.mutation.Algorithm(); ok {
		if err := request.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`ent: validator failed for field "Request.algorithm": %w`, err)}
		}
	}
	if v, ok := ru.mutation.KeyMode(); ok {
		if err := request.KeyModeValidator(v); err != nil {
			return &ValidationError{Name: "key_mode", err: fmt.Errorf(`ent: validator failed for field "Request.key_mode": %w`, err)}
		}
	}
	if _, ok := ru.mutation.UserID(); ru.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Request.user"`)
	}
	return nil
}

func (ru *RequestUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   request.Table,
			Columns: request.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: request.FieldID,
			},
		},
	}
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: request.FieldUpdatedAt,
		})
	}
	if value, ok := ru.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldStatus,
		})
	}
	if value, ok := ru.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldType,
		})
	}
	if value, ok := ru.mutation.Algorithm(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldAlgorithm,
		})
	}
	if ru.mutation.AlgorithmCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Column: request.FieldAlgorithm,
		})
	}
	if value, ok := ru.mutation.KeyMode(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldKeyMode,
		})
	}
	if ru.mutation.KeyModeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Column: request.FieldKeyMode,
		})
	}
	if value, ok := ru.mutation.ManualKeyValidation(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: request.FieldManualKeyValidation,
		})
	}
	if ru.mutation.ManualKeyValidationCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: request.FieldManualKeyValidation,
		})
	}
	if ru.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.UserTable,
			Columns: []string{request.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ru.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.UserTable,
			Columns: []string{request.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{request.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// RequestUpdateOne is the builder for updating a single Request entity.
type RequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ruo *RequestUpdateOne) SetUpdatedAt(t time.Time) *RequestUpdateOne {
	ruo.mutation.SetUpdatedAt(t)
	return ruo
}

// SetStatus sets the "status" field.
func (ruo *RequestUpdateOne) SetStatus(r request.Status) *RequestUpdateOne {
	ruo.mutation.SetStatus(r)
	return ruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ruo *RequestUpdateOne) SetNillableStatus(r *request.Status) *RequestUpdateOne {
	if r != nil {
		ruo.SetStatus(*r)
	}
	return ruo
}

// SetType sets the "type" field.
func (ruo *RequestUpdateOne) SetType(r request.Type) *RequestUpdateOne {
	ruo.mutation.SetType(r)
	return ruo
}

// SetAlgorithm sets the "algorithm" field.
func (ruo *RequestUpdateOne) SetAlgorithm(r request.Algorithm) *RequestUpdateOne {
	ruo.mutation.SetAlgorithm(r)
	return ruo
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (ruo *RequestUpdateOne) SetNillableAlgorithm(r *request.Algorithm) *RequestUpdateOne {
	if r != nil {
		ruo.SetAlgorithm(*r)
	}
	return ruo
}

// ClearAlgorithm clears the value of the "algorithm" field.
func (ruo *RequestUpdateOne) ClearAlgorithm() *RequestUpdateOne {
	ruo.mutation.ClearAlgorithm()
	return ruo
}

// SetKeyMode sets the "key_mode" field.
func (ruo *RequestUpdateOne) SetKeyMode(rm request.KeyMode) *RequestUpdateOne {
	ruo.mutation.SetKeyMode(rm)
	return ruo
}

// SetNillableKeyMode sets the "key_mode" field if the given value is not nil.
func (ruo *RequestUpdateOne) SetNillableKeyMode(rm *request.KeyMode) *RequestUpdateOne {
	if rm != nil {
		ruo.SetKeyMode(*rm)
	}
	return ruo
}

// ClearKeyMode clears the value of the "key_mode" field.
func (ruo *RequestUpdateOne) ClearKeyMode() *RequestUpdateOne {
	ruo.mutation.ClearKeyMode()
	return ruo
}

// SetManualKeyValidation sets the "manual_key_validation" field.
func (ruo *RequestUpdateOne) SetManualKeyValidation(b bool) *RequestUpdateOne {
	ruo.mutation.SetManualKeyValidation(b)
	return ruo
}

// SetNillableManualKeyValidation sets the "manual_key_validation" field if the given value is not nil.
func (ruo *RequestUpdateOne) SetNillableManualKeyValidation(b *bool) *RequestUpdateOne {
	if b != nil {
		ruo.SetManualKeyValidation(*b)
	}
	return ruo
}

// ClearManualKeyValidation clears the value of the "manual_key_validation" field.
func (ruo *RequestUpdateOne) ClearManualKeyValidation() *RequestUpdateOne {
	ruo.mutation.ClearManualKeyValidation()
	return ruo
}

// SetUserID sets the "user_id" field.
func (ruo *RequestUpdateOne) SetUserID(i int) *RequestUpdateOne {
	ruo.mutation.SetUserID(i)
	return ruo
}

// SetUser sets the "user" edge to the User entity.
func (ruo *RequestUpdateOne) SetUser(u *User) *RequestUpdateOne {
	return ruo.SetUserID(u.ID)
}

// Mutation returns the RequestMutation object of the builder.
func (ruo *RequestUpdateOne) Mutation() *RequestMutation {
	return ruo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ruo *RequestUpdateOne) ClearUser() *RequestUpdateOne {
	ruo.mutation.ClearUser()
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *RequestUpdateOne) Select(field string, fields ...string) *RequestUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Request entity.
func (ruo *RequestUpdateOne) Save(ctx context.Context) (*Request, error) {
	var (
		err  error
		node *Request
	)
	ruo.defaults()
	if len(ruo.hooks) == 0 {
		if err = ruo.check(); err != nil {
			return nil, err
		}
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RequestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ruo.check(); err != nil {
				return nil, err
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			if ruo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RequestUpdateOne) SaveX(ctx context.Context) *Request {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RequestUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RequestUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ruo *RequestUpdateOne) defaults() {
	if _, ok := ruo.mutation.UpdatedAt(); !ok {
		v := request.UpdateDefaultUpdatedAt()
		ruo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *RequestUpdateOne) check() error {
	if v, ok := ruo.mutation.Status(); ok {
		if err := request.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Request.status": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.GetType(); ok {
		if err := request.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Request.type": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.Algorithm(); ok {
		if err := request.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`ent: validator failed for field "Request.algorithm": %w`, err)}
		}
	}
	if v, ok := ruo.mutation.KeyMode(); ok {
		if err := request.KeyModeValidator(v); err != nil {
			return &ValidationError{Name: "key_mode", err: fmt.Errorf(`ent: validator failed for field "Request.key_mode": %w`, err)}
		}
	}
	if _, ok := ruo.mutation.UserID(); ruo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Request.user"`)
	}
	return nil
}

func (ruo *RequestUpdateOne) sqlSave(ctx context.Context) (_node *Request, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   request.Table,
			Columns: request.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: request.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Request.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, request.FieldID)
		for _, f := range fields {
			if !request.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != request.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: request.FieldUpdatedAt,
		})
	}
	if value, ok := ruo.mutation.Status(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldStatus,
		})
	}
	if value, ok := ruo.mutation.GetType(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldType,
		})
	}
	if value, ok := ruo.mutation.Algorithm(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldAlgorithm,
		})
	}
	if ruo.mutation.AlgorithmCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Column: request.FieldAlgorithm,
		})
	}
	if value, ok := ruo.mutation.KeyMode(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldKeyMode,
		})
	}
	if ruo.mutation.KeyModeCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Column: request.FieldKeyMode,
		})
	}
	if value, ok := ruo.mutation.ManualKeyValidation(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: request.FieldManualKeyValidation,
		})
	}
	if ruo.mutation.ManualKeyValidationCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Column: request.FieldManualKeyValidation,
		})
	}
	if ruo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.UserTable,
			Columns: []string{request.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ruo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.UserTable,
			Columns: []string{request.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Request{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{request.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
