// Code generated by entc, DO NOT EDIT.

package ent

import (
	"cipher-bot/ent/request"
	"cipher-bot/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestCreate is the builder for creating a Request entity.
type RequestCreate struct {
	config
	mutation *RequestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (rc *RequestCreate) SetCreatedAt(t time.Time) *RequestCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RequestCreate) SetNillableCreatedAt(t *time.Time) *RequestCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *RequestCreate) SetUpdatedAt(t time.Time) *RequestCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *RequestCreate) SetNillableUpdatedAt(t *time.Time) *RequestCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetStatus sets the "status" field.
func (rc *RequestCreate) SetStatus(r request.Status) *RequestCreate {
	rc.mutation.SetStatus(r)
	return rc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rc *RequestCreate) SetNillableStatus(r *request.Status) *RequestCreate {
	if r != nil {
		rc.SetStatus(*r)
	}
	return rc
}

// SetType sets the "type" field.
func (rc *RequestCreate) SetType(r request.Type) *RequestCreate {
	rc.mutation.SetType(r)
	return rc
}

// SetAlgorithm sets the "algorithm" field.
func (rc *RequestCreate) SetAlgorithm(r request.Algorithm) *RequestCreate {
	rc.mutation.SetAlgorithm(r)
	return rc
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (rc *RequestCreate) SetNillableAlgorithm(r *request.Algorithm) *RequestCreate {
	if r != nil {
		rc.SetAlgorithm(*r)
	}
	return rc
}

// SetKeyMode sets the "key_mode" field.
func (rc *RequestCreate) SetKeyMode(rm request.KeyMode) *RequestCreate {
	rc.mutation.SetKeyMode(rm)
	return rc
}

// SetNillableKeyMode sets the "key_mode" field if the given value is not nil.
func (rc *RequestCreate) SetNillableKeyMode(rm *request.KeyMode) *RequestCreate {
	if rm != nil {
		rc.SetKeyMode(*rm)
	}
	return rc
}

// SetManualKeyValidation sets the "manual_key_validation" field.
func (rc *RequestCreate) SetManualKeyValidation(b bool) *RequestCreate {
	rc.mutation.SetManualKeyValidation(b)
	return rc
}

// SetNillableManualKeyValidation sets the "manual_key_validation" field if the given value is not nil.
func (rc *RequestCreate) SetNillableManualKeyValidation(b *bool) *RequestCreate {
	if b != nil {
		rc.SetManualKeyValidation(*b)
	}
	return rc
}

// SetUserID sets the "user_id" field.
func (rc *RequestCreate) SetUserID(i int) *RequestCreate {
	rc.mutation.SetUserID(i)
	return rc
}

// SetUser sets the "user" edge to the User entity.
func (rc *RequestCreate) SetUser(u *User) *RequestCreate {
	return rc.SetUserID(u.ID)
}

// Mutation returns the RequestMutation object of the builder.
func (rc *RequestCreate) Mutation() *RequestMutation {
	return rc.mutation
}

// Save creates the Request in the database.
func (rc *RequestCreate) Save(ctx context.Context) (*Request, error) {
	var (
		err  error
		node *Request
	)
	rc.defaults()
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RequestMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RequestCreate) SaveX(ctx context.Context) *Request {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RequestCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RequestCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RequestCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := request.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := request.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
	if _, ok := rc.mutation.Status(); !ok {
		v := request.DefaultStatus
		rc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RequestCreate) check() error {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Request.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Request.updated_at"`)}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Request.status"`)}
	}
	if v, ok := rc.mutation.Status(); ok {
		if err := request.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Request.status": %w`, err)}
		}
	}
	if _, ok := rc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Request.type"`)}
	}
	if v, ok := rc.mutation.GetType(); ok {
		if err := request.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Request.type": %w`, err)}
		}
	}
	if v, ok := rc.mutation.Algorithm(); ok {
		if err := request.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`ent: validator failed for field "Request.algorithm": %w`, err)}
		}
	}
	if v, ok := rc.mutation.KeyMode(); ok {
		if err := request.KeyModeValidator(v); err != nil {
			return &ValidationError{Name: "key_mode", err: fmt.Errorf(`ent: validator failed for field "Request.key_mode": %w`, err)}
		}
	}
	if _, ok := rc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Request.user_id"`)}
	}
	if _, ok := rc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Request.user"`)}
	}
	return nil
}

func (rc *RequestCreate) sqlSave(ctx context.Context) (*Request, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rc *RequestCreate) createSpec() (*Request, *sqlgraph.CreateSpec) {
	var (
		_node = &Request{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: request.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: request.FieldID,
			},
		}
	)
	_spec.OnConflict = rc.conflict
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: request.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: request.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := rc.mutation.Status(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldStatus,
		})
		_node.Status = value
	}
	if value, ok := rc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldType,
		})
		_node.Type = value
	}
	if value, ok := rc.mutation.Algorithm(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldAlgorithm,
		})
		_node.Algorithm = &value
	}
	if value, ok := rc.mutation.KeyMode(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: request.FieldKeyMode,
		})
		_node.KeyMode = &value
	}
	if value, ok := rc.mutation.ManualKeyValidation(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: request.FieldManualKeyValidation,
		})
		_node.ManualKeyValidation = &value
	}
	if nodes := rc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.UserTable,
			Columns: []string{request.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Request.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (rc *RequestCreate) OnConflict(opts ...sql.ConflictOption) *RequestUpsertOne {
	rc.conflict = opts
	return &RequestUpsertOne{
		create: rc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (rc *RequestCreate) OnConflictColumns(columns ...string) *RequestUpsertOne {
	rc.conflict = append(rc.conflict, sql.ConflictColumns(columns...))
	return &RequestUpsertOne{
		create: rc,
	}
}

type (
	// RequestUpsertOne is the builder for "upsert"-ing
	//  one Request node.
	RequestUpsertOne struct {
		create *RequestCreate
	}

	// RequestUpsert is the "OnConflict" setter.
	RequestUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *RequestUpsert) SetCreatedAt(v time.Time) *RequestUpsert {
	u.Set(request.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RequestUpsert) UpdateCreatedAt() *RequestUpsert {
	u.SetExcluded(request.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestUpsert) SetUpdatedAt(v time.Time) *RequestUpsert {
	u.Set(request.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestUpsert) UpdateUpdatedAt() *RequestUpsert {
	u.SetExcluded(request.FieldUpdatedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *RequestUpsert) SetStatus(v request.Status) *RequestUpsert {
	u.Set(request.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestUpsert) UpdateStatus() *RequestUpsert {
	u.SetExcluded(request.FieldStatus)
	return u
}

// SetType sets the "type" field.
func (u *RequestUpsert) SetType(v request.Type) *RequestUpsert {
	u.Set(request.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RequestUpsert) UpdateType() *RequestUpsert {
	u.SetExcluded(request.FieldType)
	return u
}

// SetAlgorithm sets the "algorithm" field.
func (u *RequestUpsert) SetAlgorithm(v request.Algorithm) *RequestUpsert {
	u.Set(request.FieldAlgorithm, v)
	return u
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *RequestUpsert) UpdateAlgorithm() *RequestUpsert {
	u.SetExcluded(request.FieldAlgorithm)
	return u
}

// ClearAlgorithm clears the value of the "algorithm" field.
func (u *RequestUpsert) ClearAlgorithm() *RequestUpsert {
	u.SetNull(request.FieldAlgorithm)
	return u
}

// SetKeyMode sets the "key_mode" field.
func (u *RequestUpsert) SetKeyMode(v request.KeyMode) *RequestUpsert {
	u.Set(request.FieldKeyMode, v)
	return u
}

// UpdateKeyMode sets the "key_mode" field to the value that was provided on create.
func (u *RequestUpsert) UpdateKeyMode() *RequestUpsert {
	u.SetExcluded(request.FieldKeyMode)
	return u
}

// ClearKeyMode clears the value of the "key_mode" field.
func (u *RequestUpsert) ClearKeyMode() *RequestUpsert {
	u.SetNull(request.FieldKeyMode)
	return u
}

// SetManualKeyValidation sets the "manual_key_validation" field.
func (u *RequestUpsert) SetManualKeyValidation(v bool) *RequestUpsert {
	u.Set(request.FieldManualKeyValidation, v)
	return u
}

// UpdateManualKeyValidation sets the "manual_key_validation" field to the value that was provided on create.
func (u *RequestUpsert) UpdateManualKeyValidation() *RequestUpsert {
	u.SetExcluded(request.FieldManualKeyValidation)
	return u
}

// ClearManualKeyValidation clears the value of the "manual_key_validation" field.
func (u *RequestUpsert) ClearManualKeyValidation() *RequestUpsert {
	u.SetNull(request.FieldManualKeyValidation)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RequestUpsert) SetUserID(v int) *RequestUpsert {
	u.Set(request.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestUpsert) UpdateUserID() *RequestUpsert {
	u.SetExcluded(request.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *RequestUpsertOne) UpdateNewValues() *RequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(request.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Request.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *RequestUpsertOne) Ignore() *RequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestUpsertOne) DoNothing() *RequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestCreate.OnConflict
// documentation for more info.
func (u *RequestUpsertOne) Update(set func(*RequestUpsert)) *RequestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *RequestUpsertOne) SetCreatedAt(v time.Time) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateCreatedAt() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestUpsertOne) SetUpdatedAt(v time.Time) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateUpdatedAt() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *RequestUpsertOne) SetStatus(v request.Status) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateStatus() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateStatus()
	})
}

// SetType sets the "type" field.
func (u *RequestUpsertOne) SetType(v request.Type) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateType() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateType()
	})
}

// SetAlgorithm sets the "algorithm" field.
func (u *RequestUpsertOne) SetAlgorithm(v request.Algorithm) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetAlgorithm(v)
	})
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateAlgorithm() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateAlgorithm()
	})
}

// ClearAlgorithm clears the value of the "algorithm" field.
func (u *RequestUpsertOne) ClearAlgorithm() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.ClearAlgorithm()
	})
}

// SetKeyMode sets the "key_mode" field.
func (u *RequestUpsertOne) SetKeyMode(v request.KeyMode) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetKeyMode(v)
	})
}

// UpdateKeyMode sets the "key_mode" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateKeyMode() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateKeyMode()
	})
}

// ClearKeyMode clears the value of the "key_mode" field.
func (u *RequestUpsertOne) ClearKeyMode() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.ClearKeyMode()
	})
}

// SetManualKeyValidation sets the "manual_key_validation" field.
func (u *RequestUpsertOne) SetManualKeyValidation(v bool) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetManualKeyValidation(v)
	})
}

// UpdateManualKeyValidation sets the "manual_key_validation" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateManualKeyValidation() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateManualKeyValidation()
	})
}

// ClearManualKeyValidation clears the value of the "manual_key_validation" field.
func (u *RequestUpsertOne) ClearManualKeyValidation() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.ClearManualKeyValidation()
	})
}

// SetUserID sets the "user_id" field.
func (u *RequestUpsertOne) SetUserID(v int) *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestUpsertOne) UpdateUserID() *RequestUpsertOne {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *RequestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RequestUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RequestUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RequestCreateBulk is the builder for creating many Request entities in bulk.
type RequestCreateBulk struct {
	config
	builders []*RequestCreate
	conflict []sql.ConflictOption
}

// Save creates the Request entities in the database.
func (rcb *RequestCreateBulk) Save(ctx context.Context) ([]*Request, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Request, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = rcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RequestCreateBulk) SaveX(ctx context.Context) []*Request {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RequestCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RequestCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Request.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RequestUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (rcb *RequestCreateBulk) OnConflict(opts ...sql.ConflictOption) *RequestUpsertBulk {
	rcb.conflict = opts
	return &RequestUpsertBulk{
		create: rcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (rcb *RequestCreateBulk) OnConflictColumns(columns ...string) *RequestUpsertBulk {
	rcb.conflict = append(rcb.conflict, sql.ConflictColumns(columns...))
	return &RequestUpsertBulk{
		create: rcb,
	}
}

// RequestUpsertBulk is the builder for "upsert"-ing
// a bulk of Request nodes.
type RequestUpsertBulk struct {
	create *RequestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *RequestUpsertBulk) UpdateNewValues() *RequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(request.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Request.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *RequestUpsertBulk) Ignore() *RequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RequestUpsertBulk) DoNothing() *RequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RequestCreateBulk.OnConflict
// documentation for more info.
func (u *RequestUpsertBulk) Update(set func(*RequestUpsert)) *RequestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RequestUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *RequestUpsertBulk) SetCreatedAt(v time.Time) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateCreatedAt() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RequestUpsertBulk) SetUpdatedAt(v time.Time) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateUpdatedAt() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *RequestUpsertBulk) SetStatus(v request.Status) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateStatus() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateStatus()
	})
}

// SetType sets the "type" field.
func (u *RequestUpsertBulk) SetType(v request.Type) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateType() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateType()
	})
}

// SetAlgorithm sets the "algorithm" field.
func (u *RequestUpsertBulk) SetAlgorithm(v request.Algorithm) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetAlgorithm(v)
	})
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateAlgorithm() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateAlgorithm()
	})
}

// ClearAlgorithm clears the value of the "algorithm" field.
func (u *RequestUpsertBulk) ClearAlgorithm() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.ClearAlgorithm()
	})
}

// SetKeyMode sets the "key_mode" field.
func (u *RequestUpsertBulk) SetKeyMode(v request.KeyMode) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetKeyMode(v)
	})
}

// UpdateKeyMode sets the "key_mode" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateKeyMode() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateKeyMode()
	})
}

// ClearKeyMode clears the value of the "key_mode" field.
func (u *RequestUpsertBulk) ClearKeyMode() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.ClearKeyMode()
	})
}

// SetManualKeyValidation sets the "manual_key_validation" field.
func (u *RequestUpsertBulk) SetManualKeyValidation(v bool) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetManualKeyValidation(v)
	})
}

// UpdateManualKeyValidation sets the "manual_key_validation" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateManualKeyValidation() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateManualKeyValidation()
	})
}

// ClearManualKeyValidation clears the value of the "manual_key_validation" field.
func (u *RequestUpsertBulk) ClearManualKeyValidation() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.ClearManualKeyValidation()
	})
}

// SetUserID sets the "user_id" field.
func (u *RequestUpsertBulk) SetUserID(v int) *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RequestUpsertBulk) UpdateUserID() *RequestUpsertBulk {
	return u.Update(func(s *RequestUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *RequestUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RequestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RequestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RequestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
