// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Request is the predicate function for request builders.
type Request func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
